name: auto_deploy
on: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ISC_SERVER_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ISC_SERVER_HOST_ADDRESS }}
          REMOTE_USER: ${{ secrets.ISC_SERVER_USER }}
          TARGET: ${{ secrets.WORK_TARGEAT_PATH }} 
